/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DocumentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getDocument" | "isDocumentValid" | "issueDocument" | "owner" | "renounceOwnership" | "revokeDocument" | "totalDocuments" | "totalRevoked" | "transferOwnership" | "verifyHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DocumentIssued" | "DocumentRevoked" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'getDocument', values: [string]): string;
encodeFunctionData(functionFragment: 'isDocumentValid', values: [string]): string;
encodeFunctionData(functionFragment: 'issueDocument', values: [string, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeDocument', values: [string]): string;
encodeFunctionData(functionFragment: 'totalDocuments', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRevoked', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyHash', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDocumentValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDocuments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRevoked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHash', data: BytesLike): Result;
  }

  
    export namespace DocumentIssuedEvent {
      export type InputTuple = [docId: string, documentHash: BytesLike, issuer: AddressLike, issuedAt: BigNumberish];
      export type OutputTuple = [docId: string, documentHash: string, issuer: string, issuedAt: bigint];
      export interface OutputObject {docId: string, documentHash: string, issuer: string, issuedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DocumentRevokedEvent {
      export type InputTuple = [docId: string, revokedBy: AddressLike, revokedAt: BigNumberish];
      export type OutputTuple = [docId: string, revokedBy: string, revokedAt: bigint];
      export interface OutputObject {docId: string, revokedBy: string, revokedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DocumentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): DocumentRegistry;
    waitForDeployment(): Promise<this>;

    interface: DocumentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getDocument: TypedContractMethod<
      [docId: string, ],
      [[string, string, bigint, boolean, boolean] & {documentHash: string, issuer: string, issuedAt: bigint, isActive: boolean, exists: boolean }],
      'view'
    >
    

    
    isDocumentValid: TypedContractMethod<
      [docId: string, ],
      [boolean],
      'view'
    >
    

    
    issueDocument: TypedContractMethod<
      [docId: string, docHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeDocument: TypedContractMethod<
      [docId: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalDocuments: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRevoked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyHash: TypedContractMethod<
      [docId: string, hash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getDocument'): TypedContractMethod<
      [docId: string, ],
      [[string, string, bigint, boolean, boolean] & {documentHash: string, issuer: string, issuedAt: bigint, isActive: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'isDocumentValid'): TypedContractMethod<
      [docId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueDocument'): TypedContractMethod<
      [docId: string, docHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeDocument'): TypedContractMethod<
      [docId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDocuments'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRevoked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyHash'): TypedContractMethod<
      [docId: string, hash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'DocumentIssued'): TypedContractEvent<DocumentIssuedEvent.InputTuple, DocumentIssuedEvent.OutputTuple, DocumentIssuedEvent.OutputObject>;
getEvent(key: 'DocumentRevoked'): TypedContractEvent<DocumentRevokedEvent.InputTuple, DocumentRevokedEvent.OutputTuple, DocumentRevokedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'DocumentIssued(string,bytes32,address,uint256)': TypedContractEvent<DocumentIssuedEvent.InputTuple, DocumentIssuedEvent.OutputTuple, DocumentIssuedEvent.OutputObject>;
      DocumentIssued: TypedContractEvent<DocumentIssuedEvent.InputTuple, DocumentIssuedEvent.OutputTuple, DocumentIssuedEvent.OutputObject>;
    

      'DocumentRevoked(string,address,uint256)': TypedContractEvent<DocumentRevokedEvent.InputTuple, DocumentRevokedEvent.OutputTuple, DocumentRevokedEvent.OutputObject>;
      DocumentRevoked: TypedContractEvent<DocumentRevokedEvent.InputTuple, DocumentRevokedEvent.OutputTuple, DocumentRevokedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }