/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DocumentRegistry } from './DocumentRegistry.js';
export * as factories from './factories/index.js';
export { DocumentRegistry__factory } from './factories/DocumentRegistry__factory.js';